### ISSUE TITLE
Spring integration

### ISSUE THREAD

**Issue by bsideup** [Netflix/glisten#31]
Hi! 

Can I get some docs how to integrate Glisten with Spring? For example, how to autowire some dependencies in workflow 

Thanks!

**Comment by mooreds** [comment]
@bsideup I would love to see that example if you can make it available.

**Comment by fzakaria** [comment]
There is the Flow Spring package as well that includes SpringWorkflowWorker, which I think does something similar.
They also recommend setting the Workflow to a special scope they define.
